# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Sat Jun 24 15:04:57 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(2665, 1606)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.widgetTabs = QtGui.QWidget(MainWindow)
        self.widgetTabs.setObjectName(_fromUtf8("widgetTabs"))
        self.gridLayout = QtGui.QGridLayout(self.widgetTabs)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.widgetTabs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPressureLevel = QtGui.QWidget()
        self.tabPressureLevel.setObjectName(_fromUtf8("tabPressureLevel"))
        self.tabLayoutPressureLevel = QtGui.QVBoxLayout(self.tabPressureLevel)
        self.tabLayoutPressureLevel.setObjectName(_fromUtf8("tabLayoutPressureLevel"))
        self.plotPressure = MatplotlibWidget(self.tabPressureLevel)
        self.plotPressure.setObjectName(_fromUtf8("plotPressure"))
        self.tabLayoutPressureLevel.addWidget(self.plotPressure)
        self.tabWidget.addTab(self.tabPressureLevel, _fromUtf8(""))
        self.tabIntensityLevel = QtGui.QWidget()
        self.tabIntensityLevel.setObjectName(_fromUtf8("tabIntensityLevel"))
        self.tabLayoutIntensityLevel = QtGui.QGridLayout(self.tabIntensityLevel)
        self.tabLayoutIntensityLevel.setObjectName(_fromUtf8("tabLayoutIntensityLevel"))
        self.plotIntensity = MatplotlibWidget(self.tabIntensityLevel)
        self.plotIntensity.setObjectName(_fromUtf8("plotIntensity"))
        self.tabLayoutIntensityLevel.addWidget(self.plotIntensity, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIntensityLevel, _fromUtf8(""))
        self.tabWindowLevel = QtGui.QWidget()
        self.tabWindowLevel.setObjectName(_fromUtf8("tabWindowLevel"))
        self.tabLayoutLevel = QtGui.QGridLayout(self.tabWindowLevel)
        self.tabLayoutLevel.setObjectName(_fromUtf8("tabLayoutLevel"))
        self.plotWindowLevel = MatplotlibWidget(self.tabWindowLevel)
        self.plotWindowLevel.setObjectName(_fromUtf8("plotWindowLevel"))
        self.tabLayoutLevel.addWidget(self.plotWindowLevel, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWindowLevel, _fromUtf8(""))
        self.tabFilter = QtGui.QWidget()
        self.tabFilter.setObjectName(_fromUtf8("tabFilter"))
        self.tabLayoutFilter = QtGui.QGridLayout(self.tabFilter)
        self.tabLayoutFilter.setObjectName(_fromUtf8("tabLayoutFilter"))
        self.plotFilter = MatplotlibWidget(self.tabFilter)
        self.plotFilter.setObjectName(_fromUtf8("plotFilter"))
        self.tabLayoutFilter.addWidget(self.plotFilter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabFilter, _fromUtf8(""))
        self.tabSpectrogram = QtGui.QWidget()
        self.tabSpectrogram.setObjectName(_fromUtf8("tabSpectrogram"))
        self.tabLayoutSpectrogram = QtGui.QGridLayout(self.tabSpectrogram)
        self.tabLayoutSpectrogram.setObjectName(_fromUtf8("tabLayoutSpectrogram"))
        self.plotSpectrogram = MatplotlibWidget(self.tabSpectrogram)
        self.plotSpectrogram.setObjectName(_fromUtf8("plotSpectrogram"))
        self.tabLayoutSpectrogram.addWidget(self.plotSpectrogram, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpectrogram, _fromUtf8(""))
        self.tabFloorplan = QtGui.QWidget()
        self.tabFloorplan.setObjectName(_fromUtf8("tabFloorplan"))
        self.tabLayoutFloorplan = QtGui.QGridLayout(self.tabFloorplan)
        self.tabLayoutFloorplan.setObjectName(_fromUtf8("tabLayoutFloorplan"))
        self.plotFloorplan = MatplotlibWidget(self.tabFloorplan)
        self.plotFloorplan.setObjectName(_fromUtf8("plotFloorplan"))
        self.tabLayoutFloorplan.addWidget(self.plotFloorplan, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabFloorplan, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.widgetTabs)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2665, 38))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFIle = QtGui.QMenu(self.menubar)
        self.menuFIle.setObjectName(_fromUtf8("menuFIle"))
        self.menuProcessing = QtGui.QMenu(self.menubar)
        self.menuProcessing.setObjectName(_fromUtf8("menuProcessing"))
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menuConfiguration.setFont(font)
        self.menuConfiguration.setObjectName(_fromUtf8("menuConfiguration"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuMeasurement = QtGui.QMenu(self.menubar)
        self.menuMeasurement.setObjectName(_fromUtf8("menuMeasurement"))
        MainWindow.setMenuBar(self.menubar)
        self.dockAudio = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockAudio.sizePolicy().hasHeightForWidth())
        self.dockAudio.setSizePolicy(sizePolicy)
        self.dockAudio.setMinimumSize(QtCore.QSize(874, 338))
        self.dockAudio.setMaximumSize(QtCore.QSize(1200, 338))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dockAudio.setFont(font)
        self.dockAudio.setFloating(False)
        self.dockAudio.setObjectName(_fromUtf8("dockAudio"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.boxWindowing = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxWindowing.sizePolicy().hasHeightForWidth())
        self.boxWindowing.setSizePolicy(sizePolicy)
        self.boxWindowing.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.boxWindowing.setFont(font)
        self.boxWindowing.setAlignment(QtCore.Qt.AlignCenter)
        self.boxWindowing.setObjectName(_fromUtf8("boxWindowing"))
        self.verticalLayout = QtGui.QVBoxLayout(self.boxWindowing)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelWindowSize = QtGui.QLabel(self.boxWindowing)
        self.labelWindowSize.setMinimumSize(QtCore.QSize(0, 0))
        self.labelWindowSize.setMaximumSize(QtCore.QSize(282, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelWindowSize.setFont(font)
        self.labelWindowSize.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWindowSize.setObjectName(_fromUtf8("labelWindowSize"))
        self.horizontalLayout_3.addWidget(self.labelWindowSize)
        self.windowingWindowSize = QtGui.QDoubleSpinBox(self.boxWindowing)
        self.windowingWindowSize.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.windowingWindowSize.setFont(font)
        self.windowingWindowSize.setMaximum(10000.0)
        self.windowingWindowSize.setProperty("value", 1.0)
        self.windowingWindowSize.setObjectName(_fromUtf8("windowingWindowSize"))
        self.horizontalLayout_3.addWidget(self.windowingWindowSize)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.labelQuantity = QtGui.QLabel(self.boxWindowing)
        self.labelQuantity.setEnabled(True)
        self.labelQuantity.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelQuantity.setFont(font)
        self.labelQuantity.setAlignment(QtCore.Qt.AlignCenter)
        self.labelQuantity.setObjectName(_fromUtf8("labelQuantity"))
        self.horizontalLayout_2.addWidget(self.labelQuantity)
        self.windowingQuantity = QtGui.QSpinBox(self.boxWindowing)
        self.windowingQuantity.setMinimumSize(QtCore.QSize(170, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.windowingQuantity.setFont(font)
        self.windowingQuantity.setMaximum(9999)
        self.windowingQuantity.setProperty("value", 256)
        self.windowingQuantity.setObjectName(_fromUtf8("windowingQuantity"))
        self.horizontalLayout_2.addWidget(self.windowingQuantity)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelBounded = QtGui.QLabel(self.boxWindowing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBounded.sizePolicy().hasHeightForWidth())
        self.labelBounded.setSizePolicy(sizePolicy)
        self.labelBounded.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelBounded.setFont(font)
        self.labelBounded.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBounded.setObjectName(_fromUtf8("labelBounded"))
        self.horizontalLayout.addWidget(self.labelBounded)
        self.labelExtended = QtGui.QLabel(self.boxWindowing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelExtended.sizePolicy().hasHeightForWidth())
        self.labelExtended.setSizePolicy(sizePolicy)
        self.labelExtended.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelExtended.setFont(font)
        self.labelExtended.setAlignment(QtCore.Qt.AlignCenter)
        self.labelExtended.setObjectName(_fromUtf8("labelExtended"))
        self.horizontalLayout.addWidget(self.labelExtended)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.boundedExtended = QtGui.QSlider(self.boxWindowing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boundedExtended.sizePolicy().hasHeightForWidth())
        self.boundedExtended.setSizePolicy(sizePolicy)
        self.boundedExtended.setToolTip(_fromUtf8(""))
        self.boundedExtended.setStatusTip(_fromUtf8(""))
        self.boundedExtended.setMaximum(1)
        self.boundedExtended.setOrientation(QtCore.Qt.Horizontal)
        self.boundedExtended.setObjectName(_fromUtf8("boundedExtended"))
        self.verticalLayout.addWidget(self.boundedExtended)
        self.horizontalLayout_5.addWidget(self.boxWindowing)
        self.boxAudioEditing = QtGui.QGroupBox(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxAudioEditing.sizePolicy().hasHeightForWidth())
        self.boxAudioEditing.setSizePolicy(sizePolicy)
        self.boxAudioEditing.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boxAudioEditing.setFont(font)
        self.boxAudioEditing.setAlignment(QtCore.Qt.AlignCenter)
        self.boxAudioEditing.setObjectName(_fromUtf8("boxAudioEditing"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.boxAudioEditing)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.labelAudioCutter = QtGui.QLabel(self.boxAudioEditing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAudioCutter.sizePolicy().hasHeightForWidth())
        self.labelAudioCutter.setSizePolicy(sizePolicy)
        self.labelAudioCutter.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelAudioCutter.setFont(font)
        self.labelAudioCutter.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAudioCutter.setObjectName(_fromUtf8("labelAudioCutter"))
        self.horizontalLayout_8.addWidget(self.labelAudioCutter)
        self.audioCutter = QtGui.QDoubleSpinBox(self.boxAudioEditing)
        self.audioCutter.setEnabled(True)
        self.audioCutter.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.audioCutter.setFont(font)
        self.audioCutter.setMouseTracking(True)
        self.audioCutter.setDecimals(0)
        self.audioCutter.setMaximum(99999.0)
        self.audioCutter.setObjectName(_fromUtf8("audioCutter"))
        self.horizontalLayout_8.addWidget(self.audioCutter)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.lowPassFiltering_2 = QtGui.QLabel(self.boxAudioEditing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowPassFiltering_2.sizePolicy().hasHeightForWidth())
        self.lowPassFiltering_2.setSizePolicy(sizePolicy)
        self.lowPassFiltering_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lowPassFiltering_2.setFont(font)
        self.lowPassFiltering_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lowPassFiltering_2.setObjectName(_fromUtf8("lowPassFiltering_2"))
        self.horizontalLayout_6.addWidget(self.lowPassFiltering_2)
        self.lowPassFiltering = QtGui.QDoubleSpinBox(self.boxAudioEditing)
        self.lowPassFiltering.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lowPassFiltering.setFont(font)
        self.lowPassFiltering.setDecimals(0)
        self.lowPassFiltering.setMaximum(100000.0)
        self.lowPassFiltering.setProperty("value", 5000.0)
        self.lowPassFiltering.setObjectName(_fromUtf8("lowPassFiltering"))
        self.horizontalLayout_6.addWidget(self.lowPassFiltering)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.labelBandPassFiltering = QtGui.QLabel(self.boxAudioEditing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBandPassFiltering.sizePolicy().hasHeightForWidth())
        self.labelBandPassFiltering.setSizePolicy(sizePolicy)
        self.labelBandPassFiltering.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labelBandPassFiltering.setFont(font)
        self.labelBandPassFiltering.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBandPassFiltering.setObjectName(_fromUtf8("labelBandPassFiltering"))
        self.horizontalLayout_4.addWidget(self.labelBandPassFiltering)
        self.bandPassFiltering = QtGui.QComboBox(self.boxAudioEditing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bandPassFiltering.sizePolicy().hasHeightForWidth())
        self.bandPassFiltering.setSizePolicy(sizePolicy)
        self.bandPassFiltering.setMinimumSize(QtCore.QSize(220, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bandPassFiltering.setFont(font)
        self.bandPassFiltering.setObjectName(_fromUtf8("bandPassFiltering"))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.bandPassFiltering)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addWidget(self.boxAudioEditing)
        self.dockAudio.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockAudio)
        self.dockMeasurement = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockMeasurement.sizePolicy().hasHeightForWidth())
        self.dockMeasurement.setSizePolicy(sizePolicy)
        self.dockMeasurement.setMinimumSize(QtCore.QSize(876, 340))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dockMeasurement.setFont(font)
        self.dockMeasurement.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockMeasurement.setObjectName(_fromUtf8("dockMeasurement"))
        self.layoutHorizontalMeasurements = QtGui.QWidget()
        self.layoutHorizontalMeasurements.setObjectName(_fromUtf8("layoutHorizontalMeasurements"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutHorizontalMeasurements)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.boxMeasurementBtn = QtGui.QGroupBox(self.layoutHorizontalMeasurements)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxMeasurementBtn.sizePolicy().hasHeightForWidth())
        self.boxMeasurementBtn.setSizePolicy(sizePolicy)
        self.boxMeasurementBtn.setMinimumSize(QtCore.QSize(840, 0))
        self.boxMeasurementBtn.setTitle(_fromUtf8(""))
        self.boxMeasurementBtn.setObjectName(_fromUtf8("boxMeasurementBtn"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.boxMeasurementBtn)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnSelect = QtGui.QPushButton(self.boxMeasurementBtn)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSelect.setFont(font)
        self.btnSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSelect.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnSelect.setObjectName(_fromUtf8("btnSelect"))
        self.horizontalLayout_7.addWidget(self.btnSelect)
        self.btnLocate = QtGui.QPushButton(self.boxMeasurementBtn)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLocate.setFont(font)
        self.btnLocate.setObjectName(_fromUtf8("btnLocate"))
        self.horizontalLayout_7.addWidget(self.btnLocate)
        self.btnDelete = QtGui.QPushButton(self.boxMeasurementBtn)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDelete.setFont(font)
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDelete.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout_7.addWidget(self.btnDelete)
        self.btnDeleteAll = QtGui.QPushButton(self.boxMeasurementBtn)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDeleteAll.setFont(font)
        self.btnDeleteAll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDeleteAll.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnDeleteAll.setObjectName(_fromUtf8("btnDeleteAll"))
        self.horizontalLayout_7.addWidget(self.btnDeleteAll)
        self.gridLayout_2.addWidget(self.boxMeasurementBtn, 0, 0, 1, 1)
        self.listMeasurements = QtGui.QTableWidget(self.layoutHorizontalMeasurements)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listMeasurements.sizePolicy().hasHeightForWidth())
        self.listMeasurements.setSizePolicy(sizePolicy)
        self.listMeasurements.setMinimumSize(QtCore.QSize(820, 0))
        self.listMeasurements.setDragDropOverwriteMode(False)
        self.listMeasurements.setObjectName(_fromUtf8("listMeasurements"))
        self.listMeasurements.setColumnCount(3)
        self.listMeasurements.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.listMeasurements.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.listMeasurements.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.listMeasurements.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.listMeasurements, 1, 0, 1, 1)
        self.dockMeasurement.setWidget(self.layoutHorizontalMeasurements)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockMeasurement)
        self.dockView = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockView.sizePolicy().hasHeightForWidth())
        self.dockView.setSizePolicy(sizePolicy)
        self.dockView.setMinimumSize(QtCore.QSize(1204, 131))
        self.dockView.setFloating(False)
        self.dockView.setObjectName(_fromUtf8("dockView"))
        self.layoutGridView = QtGui.QWidget()
        self.layoutGridView.setObjectName(_fromUtf8("layoutGridView"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutGridView)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.progressBar = QtGui.QProgressBar(self.layoutGridView)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_4.addWidget(self.progressBar, 0, 0, 1, 1)
        self.btnRecalculate = QtGui.QPushButton(self.layoutGridView)
        self.btnRecalculate.setMinimumSize(QtCore.QSize(160, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnRecalculate.setFont(font)
        self.btnRecalculate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRecalculate.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnRecalculate.setObjectName(_fromUtf8("btnRecalculate"))
        self.gridLayout_4.addWidget(self.btnRecalculate, 0, 4, 1, 1)
        self.layoutXScale = QtGui.QHBoxLayout()
        self.layoutXScale.setObjectName(_fromUtf8("layoutXScale"))
        self.labelXScale = QtGui.QLabel(self.layoutGridView)
        self.labelXScale.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelXScale.setFont(font)
        self.labelXScale.setObjectName(_fromUtf8("labelXScale"))
        self.layoutXScale.addWidget(self.labelXScale)
        self.xScale = QtGui.QComboBox(self.layoutGridView)
        self.xScale.setMinimumSize(QtCore.QSize(120, 32))
        self.xScale.setObjectName(_fromUtf8("xScale"))
        self.layoutXScale.addWidget(self.xScale)
        self.gridLayout_4.addLayout(self.layoutXScale, 0, 2, 1, 1)
        self.showDetection = QtGui.QCheckBox(self.layoutGridView)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showDetection.setFont(font)
        self.showDetection.setObjectName(_fromUtf8("showDetection"))
        self.gridLayout_4.addWidget(self.showDetection, 0, 1, 1, 1)
        self.layoutYScale = QtGui.QHBoxLayout()
        self.layoutYScale.setObjectName(_fromUtf8("layoutYScale"))
        self.labelYScale = QtGui.QLabel(self.layoutGridView)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelYScale.setFont(font)
        self.labelYScale.setObjectName(_fromUtf8("labelYScale"))
        self.layoutYScale.addWidget(self.labelYScale)
        self.yScale = QtGui.QComboBox(self.layoutGridView)
        self.yScale.setMinimumSize(QtCore.QSize(120, 32))
        self.yScale.setObjectName(_fromUtf8("yScale"))
        self.layoutYScale.addWidget(self.yScale)
        self.gridLayout_4.addLayout(self.layoutYScale, 0, 3, 1, 1)
        self.dockView.setWidget(self.layoutGridView)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockView)
        self.dock3d = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock3d.sizePolicy().hasHeightForWidth())
        self.dock3d.setSizePolicy(sizePolicy)
        self.dock3d.setMinimumSize(QtCore.QSize(874, 74))
        self.dock3d.setObjectName(_fromUtf8("dock3d"))
        self.widget3d = QtGui.QWidget()
        self.widget3d.setObjectName(_fromUtf8("widget3d"))
        self.dock3d.setWidget(self.widget3d)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock3d)
        self.actionNew_project = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionNew_project.setFont(font)
        self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
        self.actionImport_Measurement = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionImport_Measurement.setFont(font)
        self.actionImport_Measurement.setObjectName(_fromUtf8("actionImport_Measurement"))
        self.actionA_to_B_convertion = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionA_to_B_convertion.setFont(font)
        self.actionA_to_B_convertion.setObjectName(_fromUtf8("actionA_to_B_convertion"))
        self.actionImport_Floorplan = QtGui.QAction(MainWindow)
        self.actionImport_Floorplan.setObjectName(_fromUtf8("actionImport_Floorplan"))
        self.menuFIle.addAction(self.actionNew_project)
        self.menuFIle.addAction(self.actionImport_Measurement)
        self.menuFIle.addAction(self.actionImport_Floorplan)
        self.menuProcessing.addAction(self.actionA_to_B_convertion)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuMeasurement.menuAction())
        self.menubar.addAction(self.menuProcessing.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPressureLevel), _translate("MainWindow", "Pressure Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIntensityLevel), _translate("MainWindow", "Intensity Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWindowLevel), _translate("MainWindow", "Window Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFilter), _translate("MainWindow", "Filtro", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpectrogram), _translate("MainWindow", "Spectrogram", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFloorplan), _translate("MainWindow", "Floorplan", None))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle", None))
        self.menuProcessing.setTitle(_translate("MainWindow", "Processing", None))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuMeasurement.setTitle(_translate("MainWindow", "Measurement", None))
        self.dockAudio.setWindowTitle(_translate("MainWindow", "Measurement Config", None))
        self.boxWindowing.setTitle(_translate("MainWindow", "Windowing", None))
        self.labelWindowSize.setText(_translate("MainWindow", "Window size", None))
        self.windowingWindowSize.setSuffix(_translate("MainWindow", " ms", None))
        self.labelQuantity.setText(_translate("MainWindow", "Quantity", None))
        self.labelBounded.setText(_translate("MainWindow", "Bounded", None))
        self.labelExtended.setText(_translate("MainWindow", "Extended", None))
        self.boxAudioEditing.setTitle(_translate("MainWindow", "Audio Editing", None))
        self.labelAudioCutter.setText(_translate("MainWindow", "Audio Cutter", None))
        self.audioCutter.setSuffix(_translate("MainWindow", " ms", None))
        self.lowPassFiltering_2.setText(_translate("MainWindow", "Low Pass Filtering", None))
        self.lowPassFiltering.setSuffix(_translate("MainWindow", " hz", None))
        self.labelBandPassFiltering.setText(_translate("MainWindow", "Band Pass Filtering", None))
        self.bandPassFiltering.setItemText(0, _translate("MainWindow", "Not applied", None))
        self.bandPassFiltering.setItemText(1, _translate("MainWindow", "Octave Band: 16Hz", None))
        self.bandPassFiltering.setItemText(2, _translate("MainWindow", "Octave Band: 31.5Hz", None))
        self.bandPassFiltering.setItemText(3, _translate("MainWindow", "Octave Band: 63Hz", None))
        self.bandPassFiltering.setItemText(4, _translate("MainWindow", "Octave Band: 125Hz", None))
        self.bandPassFiltering.setItemText(5, _translate("MainWindow", "Octave Band: 250Hz", None))
        self.bandPassFiltering.setItemText(6, _translate("MainWindow", "Octave Band: 500Hz", None))
        self.bandPassFiltering.setItemText(7, _translate("MainWindow", "Octave Band: 1000Hz", None))
        self.bandPassFiltering.setItemText(8, _translate("MainWindow", "Octave Band: 2000Hz", None))
        self.bandPassFiltering.setItemText(9, _translate("MainWindow", "Octave Band: 4000Hz", None))
        self.bandPassFiltering.setItemText(10, _translate("MainWindow", "Octave Band: 8000Hz", None))
        self.bandPassFiltering.setItemText(11, _translate("MainWindow", "Octave Band: 16000Hz", None))
        self.bandPassFiltering.setItemText(12, _translate("MainWindow", "1/3 Octave Band: 12.5Hz", None))
        self.bandPassFiltering.setItemText(13, _translate("MainWindow", "1/3 Octave Band: 16Hz", None))
        self.bandPassFiltering.setItemText(14, _translate("MainWindow", "1/3 Octave Band: 20Hz", None))
        self.bandPassFiltering.setItemText(15, _translate("MainWindow", "1/3 Octave Band: 25Hz", None))
        self.bandPassFiltering.setItemText(16, _translate("MainWindow", "1/3 Octave Band: 31.5Hz", None))
        self.bandPassFiltering.setItemText(17, _translate("MainWindow", "1/3 Octave Band: 40Hz", None))
        self.bandPassFiltering.setItemText(18, _translate("MainWindow", "1/3 Octave Band: 50Hz", None))
        self.bandPassFiltering.setItemText(19, _translate("MainWindow", "1/3 Octave Band: 63Hz", None))
        self.bandPassFiltering.setItemText(20, _translate("MainWindow", "1/3 Octave Band: 80Hz", None))
        self.bandPassFiltering.setItemText(21, _translate("MainWindow", "1/3 Octave Band: 100Hz", None))
        self.bandPassFiltering.setItemText(22, _translate("MainWindow", "1/3 Octave Band: 125Hz", None))
        self.bandPassFiltering.setItemText(23, _translate("MainWindow", "1/3 Octave Band: 160Hz", None))
        self.bandPassFiltering.setItemText(24, _translate("MainWindow", "1/3 Octave Band: 200Hz", None))
        self.bandPassFiltering.setItemText(25, _translate("MainWindow", "1/3 Octave Band: 250Hz", None))
        self.bandPassFiltering.setItemText(26, _translate("MainWindow", "1/3 Octave Band: 315Hz", None))
        self.bandPassFiltering.setItemText(27, _translate("MainWindow", "1/3 Octave Band: 400Hz", None))
        self.bandPassFiltering.setItemText(28, _translate("MainWindow", "1/3 Octave Band: 500Hz", None))
        self.bandPassFiltering.setItemText(29, _translate("MainWindow", "1/3 Octave Band: 630Hz", None))
        self.bandPassFiltering.setItemText(30, _translate("MainWindow", "1/3 Octave Band: 800Hz", None))
        self.bandPassFiltering.setItemText(31, _translate("MainWindow", "1/3 Octave Band: 1000Hz", None))
        self.bandPassFiltering.setItemText(32, _translate("MainWindow", "1/3 Octave Band: 1250Hz", None))
        self.bandPassFiltering.setItemText(33, _translate("MainWindow", "1/3 Octave Band: 1600Hz", None))
        self.bandPassFiltering.setItemText(34, _translate("MainWindow", "1/3 Octave Band: 2000Hz", None))
        self.bandPassFiltering.setItemText(35, _translate("MainWindow", "1/3 Octave Band: 2500Hz", None))
        self.bandPassFiltering.setItemText(36, _translate("MainWindow", "1/3 Octave Band: 3150Hz", None))
        self.bandPassFiltering.setItemText(37, _translate("MainWindow", "1/3 Octave Band: 4000Hz", None))
        self.bandPassFiltering.setItemText(38, _translate("MainWindow", "1/3 Octave Band: 5000Hz", None))
        self.bandPassFiltering.setItemText(39, _translate("MainWindow", "1/3 Octave Band: 6300Hz", None))
        self.bandPassFiltering.setItemText(40, _translate("MainWindow", "1/3 Octave Band: 8000Hz", None))
        self.bandPassFiltering.setItemText(41, _translate("MainWindow", "1/3 Octave Band: 10000Hz", None))
        self.bandPassFiltering.setItemText(42, _translate("MainWindow", "1/3 Octave Band: 12500Hz", None))
        self.bandPassFiltering.setItemText(43, _translate("MainWindow", "1/3 Octave Band: 16000Hz", None))
        self.bandPassFiltering.setItemText(44, _translate("MainWindow", "1/3 Octave Band: 20000Hz", None))
        self.dockMeasurement.setWindowTitle(_translate("MainWindow", "Measurements", None))
        self.btnSelect.setText(_translate("MainWindow", "Select", None))
        self.btnLocate.setText(_translate("MainWindow", "Locate", None))
        self.btnDelete.setText(_translate("MainWindow", "Delete", None))
        self.btnDeleteAll.setText(_translate("MainWindow", "Delete all", None))
        item = self.listMeasurements.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.listMeasurements.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date", None))
        item = self.listMeasurements.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Source", None))
        self.dockView.setWindowTitle(_translate("MainWindow", "2D Visualization", None))
        self.btnRecalculate.setText(_translate("MainWindow", "RECALCULATE", None))
        self.labelXScale.setText(_translate("MainWindow", "X Scale", None))
        self.showDetection.setText(_translate("MainWindow", "Show detections", None))
        self.labelYScale.setText(_translate("MainWindow", "Y Scale", None))
        self.dock3d.setWindowTitle(_translate("MainWindow", "3D Visualization", None))
        self.actionNew_project.setText(_translate("MainWindow", "New Project", None))
        self.actionImport_Measurement.setText(_translate("MainWindow", "Import Measurement", None))
        self.actionA_to_B_convertion.setText(_translate("MainWindow", "A to B convertion", None))
        self.actionImport_Floorplan.setText(_translate("MainWindow", "Import Floorplan", None))

from matplotlibwidget import MatplotlibWidget
