# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Sun Nov 20 21:48:55 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1133, 738)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.widgetTabs = QtGui.QWidget(MainWindow)
        self.widgetTabs.setObjectName(_fromUtf8("widgetTabs"))
        self.layoutWidgetTabs = QtGui.QGridLayout(self.widgetTabs)
        self.layoutWidgetTabs.setObjectName(_fromUtf8("layoutWidgetTabs"))
        self.tabWidget = QtGui.QTabWidget(self.widgetTabs)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPressureLevel = QtGui.QWidget()
        self.tabPressureLevel.setObjectName(_fromUtf8("tabPressureLevel"))
        self.tabLayoutPressureLevel = QtGui.QGridLayout(self.tabPressureLevel)
        self.tabLayoutPressureLevel.setObjectName(_fromUtf8("tabLayoutPressureLevel"))
        self.plotPressure = MatplotlibWidget(self.tabPressureLevel)
        self.plotPressure.setObjectName(_fromUtf8("plotPressure"))
        self.tabLayoutPressureLevel.addWidget(self.plotPressure, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPressureLevel, _fromUtf8(""))
        self.tabIntensityLevel = QtGui.QWidget()
        self.tabIntensityLevel.setObjectName(_fromUtf8("tabIntensityLevel"))
        self.tabLayoutIntensityLevel = QtGui.QGridLayout(self.tabIntensityLevel)
        self.tabLayoutIntensityLevel.setObjectName(_fromUtf8("tabLayoutIntensityLevel"))
        self.plotIntensity = MatplotlibWidget(self.tabIntensityLevel)
        self.plotIntensity.setObjectName(_fromUtf8("plotIntensity"))
        self.tabLayoutIntensityLevel.addWidget(self.plotIntensity, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIntensityLevel, _fromUtf8(""))
        self.tabWindowLevel = QtGui.QWidget()
        self.tabWindowLevel.setObjectName(_fromUtf8("tabWindowLevel"))
        self.tabLayoutLevel = QtGui.QGridLayout(self.tabWindowLevel)
        self.tabLayoutLevel.setObjectName(_fromUtf8("tabLayoutLevel"))
        self.plotWindowLevel = MatplotlibWidget(self.tabWindowLevel)
        self.plotWindowLevel.setObjectName(_fromUtf8("plotWindowLevel"))
        self.tabLayoutLevel.addWidget(self.plotWindowLevel, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWindowLevel, _fromUtf8(""))
        self.tabFilter = QtGui.QWidget()
        self.tabFilter.setObjectName(_fromUtf8("tabFilter"))
        self.tabLayoutFilter = QtGui.QGridLayout(self.tabFilter)
        self.tabLayoutFilter.setObjectName(_fromUtf8("tabLayoutFilter"))
        self.plotFilter = MatplotlibWidget(self.tabFilter)
        self.plotFilter.setObjectName(_fromUtf8("plotFilter"))
        self.tabLayoutFilter.addWidget(self.plotFilter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabFilter, _fromUtf8(""))
        self.tabSpectogram = QtGui.QWidget()
        self.tabSpectogram.setObjectName(_fromUtf8("tabSpectogram"))
        self.tabLayoutSpectrogram = QtGui.QGridLayout(self.tabSpectogram)
        self.tabLayoutSpectrogram.setObjectName(_fromUtf8("tabLayoutSpectrogram"))
        self.plotSpectrogram = MatplotlibWidget(self.tabSpectogram)
        self.plotSpectrogram.setObjectName(_fromUtf8("plotSpectrogram"))
        self.tabLayoutSpectrogram.addWidget(self.plotSpectrogram, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpectogram, _fromUtf8(""))
        self.layoutWidgetTabs.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.widgetTabs)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFIle = QtGui.QMenu(self.menubar)
        self.menuFIle.setObjectName(_fromUtf8("menuFIle"))
        self.menuProcessing = QtGui.QMenu(self.menubar)
        self.menuProcessing.setObjectName(_fromUtf8("menuProcessing"))
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menuConfiguration.setFont(font)
        self.menuConfiguration.setObjectName(_fromUtf8("menuConfiguration"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuMeasurement = QtGui.QMenu(self.menubar)
        self.menuMeasurement.setObjectName(_fromUtf8("menuMeasurement"))
        MainWindow.setMenuBar(self.menubar)
        self.dockAudio = QtGui.QDockWidget(MainWindow)
        self.dockAudio.setMinimumSize(QtCore.QSize(285, 333))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dockAudio.setFont(font)
        self.dockAudio.setFloating(False)
        self.dockAudio.setObjectName(_fromUtf8("dockAudio"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.boxAudioEditing = QtGui.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boxAudioEditing.setFont(font)
        self.boxAudioEditing.setAlignment(QtCore.Qt.AlignCenter)
        self.boxAudioEditing.setObjectName(_fromUtf8("boxAudioEditing"))
        self.gridLayout_3 = QtGui.QGridLayout(self.boxAudioEditing)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.layoutAudioEditing = QtGui.QVBoxLayout()
        self.layoutAudioEditing.setObjectName(_fromUtf8("layoutAudioEditing"))
        self.layoutAudioCutter = QtGui.QHBoxLayout()
        self.layoutAudioCutter.setObjectName(_fromUtf8("layoutAudioCutter"))
        self.labelAudioCutter = QtGui.QLabel(self.boxAudioEditing)
        self.labelAudioCutter.setMinimumSize(QtCore.QSize(83, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAudioCutter.setFont(font)
        self.labelAudioCutter.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAudioCutter.setObjectName(_fromUtf8("labelAudioCutter"))
        self.layoutAudioCutter.addWidget(self.labelAudioCutter)
        self.audioCutter = QtGui.QDoubleSpinBox(self.boxAudioEditing)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.audioCutter.setFont(font)
        self.audioCutter.setMouseTracking(True)
        self.audioCutter.setDecimals(0)
        self.audioCutter.setMaximum(99999.0)
        self.audioCutter.setObjectName(_fromUtf8("audioCutter"))
        self.layoutAudioCutter.addWidget(self.audioCutter)
        self.layoutAudioEditing.addLayout(self.layoutAudioCutter)
        self.layoutLowPassFiltering = QtGui.QHBoxLayout()
        self.layoutLowPassFiltering.setObjectName(_fromUtf8("layoutLowPassFiltering"))
        self.lowPassFiltering_2 = QtGui.QLabel(self.boxAudioEditing)
        self.lowPassFiltering_2.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lowPassFiltering_2.setFont(font)
        self.lowPassFiltering_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lowPassFiltering_2.setObjectName(_fromUtf8("lowPassFiltering_2"))
        self.layoutLowPassFiltering.addWidget(self.lowPassFiltering_2)
        self.lowPassFiltering = QtGui.QDoubleSpinBox(self.boxAudioEditing)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lowPassFiltering.setFont(font)
        self.lowPassFiltering.setDecimals(0)
        self.lowPassFiltering.setMaximum(100000.0)
        self.lowPassFiltering.setProperty("value", 5000.0)
        self.lowPassFiltering.setObjectName(_fromUtf8("lowPassFiltering"))
        self.layoutLowPassFiltering.addWidget(self.lowPassFiltering)
        self.layoutAudioEditing.addLayout(self.layoutLowPassFiltering)
        self.layoutBandPassFiltering = QtGui.QHBoxLayout()
        self.layoutBandPassFiltering.setObjectName(_fromUtf8("layoutBandPassFiltering"))
        self.labelBandPassFiltering = QtGui.QLabel(self.boxAudioEditing)
        self.labelBandPassFiltering.setMinimumSize(QtCore.QSize(121, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelBandPassFiltering.setFont(font)
        self.labelBandPassFiltering.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBandPassFiltering.setObjectName(_fromUtf8("labelBandPassFiltering"))
        self.layoutBandPassFiltering.addWidget(self.labelBandPassFiltering)
        self.bandPassFiltering = QtGui.QComboBox(self.boxAudioEditing)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.bandPassFiltering.setFont(font)
        self.bandPassFiltering.setObjectName(_fromUtf8("bandPassFiltering"))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.bandPassFiltering.addItem(_fromUtf8(""))
        self.layoutBandPassFiltering.addWidget(self.bandPassFiltering)
        self.layoutAudioEditing.addLayout(self.layoutBandPassFiltering)
        self.gridLayout_3.addLayout(self.layoutAudioEditing, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.boxAudioEditing)
        self.boxWindowing = QtGui.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.boxWindowing.setFont(font)
        self.boxWindowing.setAlignment(QtCore.Qt.AlignCenter)
        self.boxWindowing.setObjectName(_fromUtf8("boxWindowing"))
        self.gridLayout_2 = QtGui.QGridLayout(self.boxWindowing)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.layoutWindowing = QtGui.QVBoxLayout()
        self.layoutWindowing.setObjectName(_fromUtf8("layoutWindowing"))
        self.layoutWindowSize = QtGui.QHBoxLayout()
        self.layoutWindowSize.setObjectName(_fromUtf8("layoutWindowSize"))
        self.labelWindowSize = QtGui.QLabel(self.boxWindowing)
        self.labelWindowSize.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelWindowSize.setFont(font)
        self.labelWindowSize.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWindowSize.setObjectName(_fromUtf8("labelWindowSize"))
        self.layoutWindowSize.addWidget(self.labelWindowSize)
        self.windowingWindowSize = QtGui.QDoubleSpinBox(self.boxWindowing)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.windowingWindowSize.setFont(font)
        self.windowingWindowSize.setMaximum(10000.0)
        self.windowingWindowSize.setProperty("value", 1.0)
        self.windowingWindowSize.setObjectName(_fromUtf8("windowingWindowSize"))
        self.layoutWindowSize.addWidget(self.windowingWindowSize)
        self.layoutWindowing.addLayout(self.layoutWindowSize)
        self.layoutQuantity = QtGui.QHBoxLayout()
        self.layoutQuantity.setObjectName(_fromUtf8("layoutQuantity"))
        self.labelQuantity = QtGui.QLabel(self.boxWindowing)
        self.labelQuantity.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelQuantity.setFont(font)
        self.labelQuantity.setAlignment(QtCore.Qt.AlignCenter)
        self.labelQuantity.setObjectName(_fromUtf8("labelQuantity"))
        self.layoutQuantity.addWidget(self.labelQuantity)
        self.windowingQuantity = QtGui.QSpinBox(self.boxWindowing)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.windowingQuantity.setFont(font)
        self.windowingQuantity.setMaximum(9999)
        self.windowingQuantity.setProperty("value", 256)
        self.windowingQuantity.setObjectName(_fromUtf8("windowingQuantity"))
        self.layoutQuantity.addWidget(self.windowingQuantity)
        self.layoutWindowing.addLayout(self.layoutQuantity)
        self.layoutBoundedExtended = QtGui.QGridLayout()
        self.layoutBoundedExtended.setObjectName(_fromUtf8("layoutBoundedExtended"))
        self.labelBounded = QtGui.QLabel(self.boxWindowing)
        self.labelBounded.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelBounded.setFont(font)
        self.labelBounded.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBounded.setObjectName(_fromUtf8("labelBounded"))
        self.layoutBoundedExtended.addWidget(self.labelBounded, 0, 0, 1, 1)
        self.labelExtended = QtGui.QLabel(self.boxWindowing)
        self.labelExtended.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelExtended.setFont(font)
        self.labelExtended.setAlignment(QtCore.Qt.AlignCenter)
        self.labelExtended.setObjectName(_fromUtf8("labelExtended"))
        self.layoutBoundedExtended.addWidget(self.labelExtended, 0, 1, 1, 1)
        self.boundedExtended = QtGui.QSlider(self.boxWindowing)
        self.boundedExtended.setToolTip(_fromUtf8(""))
        self.boundedExtended.setStatusTip(_fromUtf8(""))
        self.boundedExtended.setMaximum(1)
        self.boundedExtended.setOrientation(QtCore.Qt.Horizontal)
        self.boundedExtended.setObjectName(_fromUtf8("boundedExtended"))
        self.layoutBoundedExtended.addWidget(self.boundedExtended, 1, 0, 1, 2)
        self.layoutWindowing.addLayout(self.layoutBoundedExtended)
        self.gridLayout_2.addLayout(self.layoutWindowing, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.boxWindowing)
        self.dockAudio.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockAudio)
        self.dockMeasurement = QtGui.QDockWidget(MainWindow)
        self.dockMeasurement.setMinimumSize(QtCore.QSize(352, 173))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dockMeasurement.setFont(font)
        self.dockMeasurement.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockMeasurement.setObjectName(_fromUtf8("dockMeasurement"))
        self.layoutHorizontalMeasurements = QtGui.QWidget()
        self.layoutHorizontalMeasurements.setObjectName(_fromUtf8("layoutHorizontalMeasurements"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutHorizontalMeasurements)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.boxMeasurementBtn = QtGui.QGroupBox(self.layoutHorizontalMeasurements)
        self.boxMeasurementBtn.setTitle(_fromUtf8(""))
        self.boxMeasurementBtn.setObjectName(_fromUtf8("boxMeasurementBtn"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.boxMeasurementBtn)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnSelect = QtGui.QPushButton(self.boxMeasurementBtn)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSelect.setFont(font)
        self.btnSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSelect.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnSelect.setObjectName(_fromUtf8("btnSelect"))
        self.horizontalLayout_7.addWidget(self.btnSelect)
        self.btnDelete = QtGui.QPushButton(self.boxMeasurementBtn)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDelete.setFont(font)
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDelete.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout_7.addWidget(self.btnDelete)
        self.btnDeleteAll = QtGui.QPushButton(self.boxMeasurementBtn)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDeleteAll.setFont(font)
        self.btnDeleteAll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDeleteAll.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnDeleteAll.setObjectName(_fromUtf8("btnDeleteAll"))
        self.horizontalLayout_7.addWidget(self.btnDeleteAll)
        self.verticalLayout_4.addWidget(self.boxMeasurementBtn)
        self.listMeasurements = QtGui.QTableWidget(self.layoutHorizontalMeasurements)
        self.listMeasurements.setDragDropOverwriteMode(False)
        self.listMeasurements.setObjectName(_fromUtf8("listMeasurements"))
        self.listMeasurements.setColumnCount(3)
        self.listMeasurements.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.listMeasurements.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.listMeasurements.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.listMeasurements.setHorizontalHeaderItem(2, item)
        self.verticalLayout_4.addWidget(self.listMeasurements)
        self.dockMeasurement.setWidget(self.layoutHorizontalMeasurements)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockMeasurement)
        self.dockView = QtGui.QDockWidget(MainWindow)
        self.dockView.setMinimumSize(QtCore.QSize(842, 84))
        self.dockView.setFloating(False)
        self.dockView.setObjectName(_fromUtf8("dockView"))
        self.layoutGridView = QtGui.QWidget()
        self.layoutGridView.setObjectName(_fromUtf8("layoutGridView"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutGridView)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.progressBar = QtGui.QProgressBar(self.layoutGridView)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_4.addWidget(self.progressBar, 0, 0, 1, 1)
        self.showDetection = QtGui.QCheckBox(self.layoutGridView)
        self.showDetection.setObjectName(_fromUtf8("showDetection"))
        self.gridLayout_4.addWidget(self.showDetection, 0, 1, 1, 1)
        self.layoutXScale = QtGui.QHBoxLayout()
        self.layoutXScale.setObjectName(_fromUtf8("layoutXScale"))
        self.labelXScale = QtGui.QLabel(self.layoutGridView)
        self.labelXScale.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelXScale.setFont(font)
        self.labelXScale.setObjectName(_fromUtf8("labelXScale"))
        self.layoutXScale.addWidget(self.labelXScale)
        self.xScale = QtGui.QComboBox(self.layoutGridView)
        self.xScale.setMinimumSize(QtCore.QSize(120, 32))
        self.xScale.setObjectName(_fromUtf8("xScale"))
        self.layoutXScale.addWidget(self.xScale)
        self.gridLayout_4.addLayout(self.layoutXScale, 0, 2, 1, 1)
        self.layoutYScale = QtGui.QHBoxLayout()
        self.layoutYScale.setObjectName(_fromUtf8("layoutYScale"))
        self.labelYScale = QtGui.QLabel(self.layoutGridView)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelYScale.setFont(font)
        self.labelYScale.setObjectName(_fromUtf8("labelYScale"))
        self.layoutYScale.addWidget(self.labelYScale)
        self.yScale = QtGui.QComboBox(self.layoutGridView)
        self.yScale.setMinimumSize(QtCore.QSize(120, 32))
        self.yScale.setObjectName(_fromUtf8("yScale"))
        self.layoutYScale.addWidget(self.yScale)
        self.gridLayout_4.addLayout(self.layoutYScale, 0, 3, 1, 1)
        self.btnRecalculate = QtGui.QPushButton(self.layoutGridView)
        self.btnRecalculate.setMinimumSize(QtCore.QSize(160, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnRecalculate.setFont(font)
        self.btnRecalculate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRecalculate.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnRecalculate.setObjectName(_fromUtf8("btnRecalculate"))
        self.gridLayout_4.addWidget(self.btnRecalculate, 0, 4, 1, 1)
        self.dockView.setWidget(self.layoutGridView)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockView)
        self.actionNew_project = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionNew_project.setFont(font)
        self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
        self.actionImport_Measurement = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionImport_Measurement.setFont(font)
        self.actionImport_Measurement.setObjectName(_fromUtf8("actionImport_Measurement"))
        self.actionA_to_B_convertion = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionA_to_B_convertion.setFont(font)
        self.actionA_to_B_convertion.setObjectName(_fromUtf8("actionA_to_B_convertion"))
        self.menuFIle.addAction(self.actionNew_project)
        self.menuFIle.addAction(self.actionImport_Measurement)
        self.menuProcessing.addAction(self.actionA_to_B_convertion)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuMeasurement.menuAction())
        self.menubar.addAction(self.menuProcessing.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPressureLevel), _translate("MainWindow", "Pressure Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIntensityLevel), _translate("MainWindow", "Intensity Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWindowLevel), _translate("MainWindow", "Window Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFilter), _translate("MainWindow", "Filtro", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpectogram), _translate("MainWindow", "Spectrogram", None))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle", None))
        self.menuProcessing.setTitle(_translate("MainWindow", "Processing", None))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuMeasurement.setTitle(_translate("MainWindow", "Measurement", None))
        self.dockAudio.setWindowTitle(_translate("MainWindow", "Measurement Config", None))
        self.boxAudioEditing.setTitle(_translate("MainWindow", "Audio Editing", None))
        self.labelAudioCutter.setText(_translate("MainWindow", "Audio Cutter", None))
        self.audioCutter.setSuffix(_translate("MainWindow", " ms", None))
        self.lowPassFiltering_2.setText(_translate("MainWindow", "Low Pass Filtering", None))
        self.lowPassFiltering.setSuffix(_translate("MainWindow", " hz", None))
        self.labelBandPassFiltering.setText(_translate("MainWindow", "Band Pass Filtering", None))
        self.bandPassFiltering.setItemText(0, _translate("MainWindow", "Not applied", None))
        self.bandPassFiltering.setItemText(1, _translate("MainWindow", "Octave Band: 16Hz", None))
        self.bandPassFiltering.setItemText(2, _translate("MainWindow", "Octave Band: 31.5Hz", None))
        self.bandPassFiltering.setItemText(3, _translate("MainWindow", "Octave Band: 63Hz", None))
        self.bandPassFiltering.setItemText(4, _translate("MainWindow", "Octave Band: 125Hz", None))
        self.bandPassFiltering.setItemText(5, _translate("MainWindow", "Octave Band: 250Hz", None))
        self.bandPassFiltering.setItemText(6, _translate("MainWindow", "Octave Band: 500Hz", None))
        self.bandPassFiltering.setItemText(7, _translate("MainWindow", "Octave Band: 1000Hz", None))
        self.bandPassFiltering.setItemText(8, _translate("MainWindow", "Octave Band: 2000Hz", None))
        self.bandPassFiltering.setItemText(9, _translate("MainWindow", "Octave Band: 4000Hz", None))
        self.bandPassFiltering.setItemText(10, _translate("MainWindow", "Octave Band: 8000Hz", None))
        self.bandPassFiltering.setItemText(11, _translate("MainWindow", "Octave Band: 16000Hz", None))
        self.bandPassFiltering.setItemText(12, _translate("MainWindow", "1/3 Octave Band: 12.5Hz", None))
        self.bandPassFiltering.setItemText(13, _translate("MainWindow", "1/3 Octave Band: 16Hz", None))
        self.bandPassFiltering.setItemText(14, _translate("MainWindow", "1/3 Octave Band: 20Hz", None))
        self.bandPassFiltering.setItemText(15, _translate("MainWindow", "1/3 Octave Band: 25Hz", None))
        self.bandPassFiltering.setItemText(16, _translate("MainWindow", "1/3 Octave Band: 31.5Hz", None))
        self.bandPassFiltering.setItemText(17, _translate("MainWindow", "1/3 Octave Band: 40Hz", None))
        self.bandPassFiltering.setItemText(18, _translate("MainWindow", "1/3 Octave Band: 50Hz", None))
        self.bandPassFiltering.setItemText(19, _translate("MainWindow", "1/3 Octave Band: 63Hz", None))
        self.bandPassFiltering.setItemText(20, _translate("MainWindow", "1/3 Octave Band: 80Hz", None))
        self.bandPassFiltering.setItemText(21, _translate("MainWindow", "1/3 Octave Band: 100Hz", None))
        self.bandPassFiltering.setItemText(22, _translate("MainWindow", "1/3 Octave Band: 125Hz", None))
        self.bandPassFiltering.setItemText(23, _translate("MainWindow", "1/3 Octave Band: 160Hz", None))
        self.bandPassFiltering.setItemText(24, _translate("MainWindow", "1/3 Octave Band: 200Hz", None))
        self.bandPassFiltering.setItemText(25, _translate("MainWindow", "1/3 Octave Band: 250Hz", None))
        self.bandPassFiltering.setItemText(26, _translate("MainWindow", "1/3 Octave Band: 315Hz", None))
        self.bandPassFiltering.setItemText(27, _translate("MainWindow", "1/3 Octave Band: 400Hz", None))
        self.bandPassFiltering.setItemText(28, _translate("MainWindow", "1/3 Octave Band: 500Hz", None))
        self.bandPassFiltering.setItemText(29, _translate("MainWindow", "1/3 Octave Band: 630Hz", None))
        self.bandPassFiltering.setItemText(30, _translate("MainWindow", "1/3 Octave Band: 800Hz", None))
        self.bandPassFiltering.setItemText(31, _translate("MainWindow", "1/3 Octave Band: 1000Hz", None))
        self.bandPassFiltering.setItemText(32, _translate("MainWindow", "1/3 Octave Band: 1250Hz", None))
        self.bandPassFiltering.setItemText(33, _translate("MainWindow", "1/3 Octave Band: 1600Hz", None))
        self.bandPassFiltering.setItemText(34, _translate("MainWindow", "1/3 Octave Band: 2000Hz", None))
        self.bandPassFiltering.setItemText(35, _translate("MainWindow", "1/3 Octave Band: 2500Hz", None))
        self.bandPassFiltering.setItemText(36, _translate("MainWindow", "1/3 Octave Band: 3150Hz", None))
        self.bandPassFiltering.setItemText(37, _translate("MainWindow", "1/3 Octave Band: 4000Hz", None))
        self.bandPassFiltering.setItemText(38, _translate("MainWindow", "1/3 Octave Band: 5000Hz", None))
        self.bandPassFiltering.setItemText(39, _translate("MainWindow", "1/3 Octave Band: 6300Hz", None))
        self.bandPassFiltering.setItemText(40, _translate("MainWindow", "1/3 Octave Band: 8000Hz", None))
        self.bandPassFiltering.setItemText(41, _translate("MainWindow", "1/3 Octave Band: 10000Hz", None))
        self.bandPassFiltering.setItemText(42, _translate("MainWindow", "1/3 Octave Band: 12500Hz", None))
        self.bandPassFiltering.setItemText(43, _translate("MainWindow", "1/3 Octave Band: 16000Hz", None))
        self.bandPassFiltering.setItemText(44, _translate("MainWindow", "1/3 Octave Band: 20000Hz", None))
        self.boxWindowing.setTitle(_translate("MainWindow", "Windowing", None))
        self.labelWindowSize.setText(_translate("MainWindow", "Window size", None))
        self.windowingWindowSize.setSuffix(_translate("MainWindow", " ms", None))
        self.labelQuantity.setText(_translate("MainWindow", "Quantity", None))
        self.labelBounded.setText(_translate("MainWindow", "Bounded", None))
        self.labelExtended.setText(_translate("MainWindow", "Extended", None))
        self.dockMeasurement.setWindowTitle(_translate("MainWindow", "Measurements", None))
        self.btnSelect.setText(_translate("MainWindow", "Select", None))
        self.btnDelete.setText(_translate("MainWindow", "Delete", None))
        self.btnDeleteAll.setText(_translate("MainWindow", "Delete all", None))
        item = self.listMeasurements.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name", None))
        item = self.listMeasurements.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date", None))
        item = self.listMeasurements.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Source", None))
        self.showDetection.setText(_translate("MainWindow", "Show detections", None))
        self.labelXScale.setText(_translate("MainWindow", "X Scale", None))
        self.labelYScale.setText(_translate("MainWindow", "Y Scale", None))
        self.btnRecalculate.setText(_translate("MainWindow", "RECALCULATE", None))
        self.actionNew_project.setText(_translate("MainWindow", "New Project", None))
        self.actionImport_Measurement.setText(_translate("MainWindow", "Import Measurement", None))
        self.actionA_to_B_convertion.setText(_translate("MainWindow", "A to B convertion", None))

from matplotlibwidget import MatplotlibWidget
