# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Sun Oct 08 21:26:55 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_IRV360(object):
    def setupUi(self, IRV360):
        IRV360.setObjectName(_fromUtf8("IRV360"))
        IRV360.resize(1169, 543)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(IRV360.sizePolicy().hasHeightForWidth())
        IRV360.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        IRV360.setFont(font)
        IRV360.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        IRV360.setUnifiedTitleAndToolBarOnMac(True)
        self.widgetTabs = QtGui.QWidget(IRV360)
        self.widgetTabs.setMinimumSize(QtCore.QSize(450, 500))
        self.widgetTabs.setObjectName(_fromUtf8("widgetTabs"))
        self.gridLayout = QtGui.QGridLayout(self.widgetTabs)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.widgetTabs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPressureLevel = QtGui.QWidget()
        self.tabPressureLevel.setObjectName(_fromUtf8("tabPressureLevel"))
        self.tabLayoutPressureLevel = QtGui.QVBoxLayout(self.tabPressureLevel)
        self.tabLayoutPressureLevel.setObjectName(_fromUtf8("tabLayoutPressureLevel"))
        self.plotPressure = MatplotlibWidget(self.tabPressureLevel)
        self.plotPressure.setObjectName(_fromUtf8("plotPressure"))
        self.tabLayoutPressureLevel.addWidget(self.plotPressure)
        self.tabWidget.addTab(self.tabPressureLevel, _fromUtf8(""))
        self.tabIntensityLevel = QtGui.QWidget()
        self.tabIntensityLevel.setObjectName(_fromUtf8("tabIntensityLevel"))
        self.tabLayoutIntensityLevel = QtGui.QGridLayout(self.tabIntensityLevel)
        self.tabLayoutIntensityLevel.setObjectName(_fromUtf8("tabLayoutIntensityLevel"))
        self.plotIntensity = MatplotlibWidget(self.tabIntensityLevel)
        self.plotIntensity.setObjectName(_fromUtf8("plotIntensity"))
        self.tabLayoutIntensityLevel.addWidget(self.plotIntensity, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIntensityLevel, _fromUtf8(""))
        self.tabWindowLevel = QtGui.QWidget()
        self.tabWindowLevel.setObjectName(_fromUtf8("tabWindowLevel"))
        self.tabLayoutLevel = QtGui.QGridLayout(self.tabWindowLevel)
        self.tabLayoutLevel.setObjectName(_fromUtf8("tabLayoutLevel"))
        self.plotWindowLevel = MatplotlibWidget(self.tabWindowLevel)
        self.plotWindowLevel.setObjectName(_fromUtf8("plotWindowLevel"))
        self.tabLayoutLevel.addWidget(self.plotWindowLevel, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabWindowLevel, _fromUtf8(""))
        self.tabFilter = QtGui.QWidget()
        self.tabFilter.setObjectName(_fromUtf8("tabFilter"))
        self.tabLayoutFilter = QtGui.QGridLayout(self.tabFilter)
        self.tabLayoutFilter.setObjectName(_fromUtf8("tabLayoutFilter"))
        self.plotFilter = MatplotlibWidget(self.tabFilter)
        self.plotFilter.setObjectName(_fromUtf8("plotFilter"))
        self.tabLayoutFilter.addWidget(self.plotFilter, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabFilter, _fromUtf8(""))
        self.tabSpectrogram = QtGui.QWidget()
        self.tabSpectrogram.setObjectName(_fromUtf8("tabSpectrogram"))
        self.tabLayoutSpectrogram = QtGui.QGridLayout(self.tabSpectrogram)
        self.tabLayoutSpectrogram.setObjectName(_fromUtf8("tabLayoutSpectrogram"))
        self.plotSpectrogram = MatplotlibWidget(self.tabSpectrogram)
        self.plotSpectrogram.setObjectName(_fromUtf8("plotSpectrogram"))
        self.tabLayoutSpectrogram.addWidget(self.plotSpectrogram, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpectrogram, _fromUtf8(""))
        self.tabFloorplan = QtGui.QWidget()
        self.tabFloorplan.setObjectName(_fromUtf8("tabFloorplan"))
        self.tabLayoutFloorplan = QtGui.QGridLayout(self.tabFloorplan)
        self.tabLayoutFloorplan.setObjectName(_fromUtf8("tabLayoutFloorplan"))
        self.plotFloorplan = MatplotlibWidget(self.tabFloorplan)
        self.plotFloorplan.setObjectName(_fromUtf8("plotFloorplan"))
        self.tabLayoutFloorplan.addWidget(self.plotFloorplan, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabFloorplan, _fromUtf8(""))
        self.tabTableData = QtGui.QWidget()
        self.tabTableData.setObjectName(_fromUtf8("tabTableData"))
        self.tableDataLayout = QtGui.QGridLayout(self.tabTableData)
        self.tableDataLayout.setObjectName(_fromUtf8("tableDataLayout"))
        self.tableData = QtGui.QTableWidget(self.tabTableData)
        self.tableData.setObjectName(_fromUtf8("tableData"))
        self.tableData.setColumnCount(4)
        self.tableData.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableData.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableData.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableData.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableData.setHorizontalHeaderItem(3, item)
        self.tableDataLayout.addWidget(self.tableData, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabTableData, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        IRV360.setCentralWidget(self.widgetTabs)
        self.menubar = QtGui.QMenuBar(IRV360)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1169, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFIle = QtGui.QMenu(self.menubar)
        self.menuFIle.setObjectName(_fromUtf8("menuFIle"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuImport = QtGui.QMenu(self.menubar)
        self.menuImport.setObjectName(_fromUtf8("menuImport"))
        IRV360.setMenuBar(self.menubar)
        self.dockAudio = QtGui.QDockWidget(IRV360)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockAudio.sizePolicy().hasHeightForWidth())
        self.dockAudio.setSizePolicy(sizePolicy)
        self.dockAudio.setMinimumSize(QtCore.QSize(360, 410))
        self.dockAudio.setMaximumSize(QtCore.QSize(700, 410))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.dockAudio.setFont(font)
        self.dockAudio.setFloating(False)
        self.dockAudio.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.dockAudio.setObjectName(_fromUtf8("dockAudio"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_5.setContentsMargins(-1, -1, -1, 30)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.recalculateAndProgressBar = QtGui.QHBoxLayout()
        self.recalculateAndProgressBar.setObjectName(_fromUtf8("recalculateAndProgressBar"))
        self.btnRecalculate = QtGui.QPushButton(self.dockWidgetContents)
        self.btnRecalculate.setMinimumSize(QtCore.QSize(160, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnRecalculate.setFont(font)
        self.btnRecalculate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRecalculate.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnRecalculate.setObjectName(_fromUtf8("btnRecalculate"))
        self.recalculateAndProgressBar.addWidget(self.btnRecalculate)
        self.progressBar = QtGui.QProgressBar(self.dockWidgetContents)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.recalculateAndProgressBar.addWidget(self.progressBar)
        self.verticalLayout_5.addLayout(self.recalculateAndProgressBar)
        self.toolBoxSettings = QtGui.QToolBox(self.dockWidgetContents)
        self.toolBoxSettings.setMinimumSize(QtCore.QSize(300, 0))
        self.toolBoxSettings.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBoxSettings.setObjectName(_fromUtf8("toolBoxSettings"))
        self.Config = QtGui.QWidget()
        self.Config.setGeometry(QtCore.QRect(0, 0, 394, 230))
        self.Config.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Config.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Config.setObjectName(_fromUtf8("Config"))
        self.gridLayout_9 = QtGui.QGridLayout(self.Config)
        self.gridLayout_9.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.Layout_measurementValues = QtGui.QHBoxLayout()
        self.Layout_measurementValues.setSpacing(0)
        self.Layout_measurementValues.setObjectName(_fromUtf8("Layout_measurementValues"))
        self.boxWindowing = QtGui.QGroupBox(self.Config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxWindowing.sizePolicy().hasHeightForWidth())
        self.boxWindowing.setSizePolicy(sizePolicy)
        self.boxWindowing.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.boxWindowing.setFont(font)
        self.boxWindowing.setAlignment(QtCore.Qt.AlignCenter)
        self.boxWindowing.setObjectName(_fromUtf8("boxWindowing"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.boxWindowing)
        self.verticalLayout_13.setContentsMargins(3, 9, 3, -1)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.labelOverlapping = QtGui.QLabel(self.boxWindowing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOverlapping.sizePolicy().hasHeightForWidth())
        self.labelOverlapping.setSizePolicy(sizePolicy)
        self.labelOverlapping.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelOverlapping.setFont(font)
        self.labelOverlapping.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOverlapping.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelOverlapping.setMargin(-1)
        self.labelOverlapping.setObjectName(_fromUtf8("labelOverlapping"))
        self.verticalLayout_3.addWidget(self.labelOverlapping)
        self.Overlapping = QtGui.QComboBox(self.boxWindowing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Overlapping.sizePolicy().hasHeightForWidth())
        self.Overlapping.setSizePolicy(sizePolicy)
        self.Overlapping.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Overlapping.setFont(font)
        self.Overlapping.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Overlapping.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.Overlapping.setObjectName(_fromUtf8("Overlapping"))
        self.Overlapping.addItem(_fromUtf8(""))
        self.Overlapping.addItem(_fromUtf8(""))
        self.Overlapping.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.Overlapping)
        self.verticalLayout_13.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.labelWindowSize = QtGui.QLabel(self.boxWindowing)
        self.labelWindowSize.setMinimumSize(QtCore.QSize(0, 0))
        self.labelWindowSize.setMaximumSize(QtCore.QSize(282, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelWindowSize.setFont(font)
        self.labelWindowSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelWindowSize.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelWindowSize.setMargin(-1)
        self.labelWindowSize.setIndent(-2)
        self.labelWindowSize.setObjectName(_fromUtf8("labelWindowSize"))
        self.verticalLayout_7.addWidget(self.labelWindowSize)
        self.windowingWindowSize = QtGui.QDoubleSpinBox(self.boxWindowing)
        self.windowingWindowSize.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.windowingWindowSize.setFont(font)
        self.windowingWindowSize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.windowingWindowSize.setMaximum(10000.0)
        self.windowingWindowSize.setProperty("value", 1.0)
        self.windowingWindowSize.setObjectName(_fromUtf8("windowingWindowSize"))
        self.verticalLayout_7.addWidget(self.windowingWindowSize)
        self.verticalLayout_13.addLayout(self.verticalLayout_7)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.labelQuantity = QtGui.QLabel(self.boxWindowing)
        self.labelQuantity.setEnabled(True)
        self.labelQuantity.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelQuantity.setFont(font)
        self.labelQuantity.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelQuantity.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelQuantity.setMargin(-1)
        self.labelQuantity.setObjectName(_fromUtf8("labelQuantity"))
        self.verticalLayout_8.addWidget(self.labelQuantity)
        self.windowingQuantity = QtGui.QSpinBox(self.boxWindowing)
        self.windowingQuantity.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.windowingQuantity.setFont(font)
        self.windowingQuantity.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.windowingQuantity.setMaximum(9999)
        self.windowingQuantity.setProperty("value", 256)
        self.windowingQuantity.setObjectName(_fromUtf8("windowingQuantity"))
        self.verticalLayout_8.addWidget(self.windowingQuantity)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.thresholdLabel = QtGui.QLabel(self.boxWindowing)
        self.thresholdLabel.setEnabled(True)
        self.thresholdLabel.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.thresholdLabel.setFont(font)
        self.thresholdLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thresholdLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.thresholdLabel.setMargin(-1)
        self.thresholdLabel.setObjectName(_fromUtf8("thresholdLabel"))
        self.verticalLayout.addWidget(self.thresholdLabel)
        self.thresholdValue = QtGui.QDoubleSpinBox(self.boxWindowing)
        self.thresholdValue.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.thresholdValue.setFont(font)
        self.thresholdValue.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.thresholdValue.setDecimals(1)
        self.thresholdValue.setMaximum(10000.0)
        self.thresholdValue.setProperty("value", 40.0)
        self.thresholdValue.setObjectName(_fromUtf8("thresholdValue"))
        self.verticalLayout.addWidget(self.thresholdValue)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.Layout_measurementValues.addWidget(self.boxWindowing)
        self.boxAudioEditing = QtGui.QGroupBox(self.Config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxAudioEditing.sizePolicy().hasHeightForWidth())
        self.boxAudioEditing.setSizePolicy(sizePolicy)
        self.boxAudioEditing.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boxAudioEditing.setFont(font)
        self.boxAudioEditing.setAlignment(QtCore.Qt.AlignCenter)
        self.boxAudioEditing.setObjectName(_fromUtf8("boxAudioEditing"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.boxAudioEditing)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.labelAudioCutter = QtGui.QLabel(self.boxAudioEditing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAudioCutter.sizePolicy().hasHeightForWidth())
        self.labelAudioCutter.setSizePolicy(sizePolicy)
        self.labelAudioCutter.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelAudioCutter.setFont(font)
        self.labelAudioCutter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelAudioCutter.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelAudioCutter.setMargin(-1)
        self.labelAudioCutter.setObjectName(_fromUtf8("labelAudioCutter"))
        self.verticalLayout_6.addWidget(self.labelAudioCutter)
        self.audioCutter = QtGui.QDoubleSpinBox(self.boxAudioEditing)
        self.audioCutter.setEnabled(True)
        self.audioCutter.setMinimumSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.audioCutter.setFont(font)
        self.audioCutter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.audioCutter.setMouseTracking(True)
        self.audioCutter.setDecimals(0)
        self.audioCutter.setMaximum(99999.0)
        self.audioCutter.setObjectName(_fromUtf8("audioCutter"))
        self.verticalLayout_6.addWidget(self.audioCutter)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lowPassFiltering_2 = QtGui.QLabel(self.boxAudioEditing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowPassFiltering_2.sizePolicy().hasHeightForWidth())
        self.lowPassFiltering_2.setSizePolicy(sizePolicy)
        self.lowPassFiltering_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lowPassFiltering_2.setFont(font)
        self.lowPassFiltering_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lowPassFiltering_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lowPassFiltering_2.setMargin(-1)
        self.lowPassFiltering_2.setObjectName(_fromUtf8("lowPassFiltering_2"))
        self.verticalLayout_2.addWidget(self.lowPassFiltering_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.hi_pass_active = QtGui.QCheckBox(self.boxAudioEditing)
        self.hi_pass_active.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hi_pass_active.setFont(font)
        self.hi_pass_active.setObjectName(_fromUtf8("hi_pass_active"))
        self.horizontalLayout_3.addWidget(self.hi_pass_active)
        self.low_pass_active = QtGui.QCheckBox(self.boxAudioEditing)
        self.low_pass_active.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.low_pass_active.setFont(font)
        self.low_pass_active.setChecked(True)
        self.low_pass_active.setTristate(False)
        self.low_pass_active.setObjectName(_fromUtf8("low_pass_active"))
        self.horizontalLayout_3.addWidget(self.low_pass_active)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.hiPassFiltering = QtGui.QDoubleSpinBox(self.boxAudioEditing)
        self.hiPassFiltering.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.hiPassFiltering.setFont(font)
        self.hiPassFiltering.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hiPassFiltering.setDecimals(0)
        self.hiPassFiltering.setMaximum(100000.0)
        self.hiPassFiltering.setProperty("value", 1.0)
        self.hiPassFiltering.setObjectName(_fromUtf8("hiPassFiltering"))
        self.horizontalLayout_2.addWidget(self.hiPassFiltering)
        self.lowPassFiltering = QtGui.QDoubleSpinBox(self.boxAudioEditing)
        self.lowPassFiltering.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lowPassFiltering.setFont(font)
        self.lowPassFiltering.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lowPassFiltering.setDecimals(0)
        self.lowPassFiltering.setMaximum(100000.0)
        self.lowPassFiltering.setProperty("value", 5.0)
        self.lowPassFiltering.setObjectName(_fromUtf8("lowPassFiltering"))
        self.horizontalLayout_2.addWidget(self.lowPassFiltering)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.labelOverlapping_2 = QtGui.QLabel(self.boxAudioEditing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOverlapping_2.sizePolicy().hasHeightForWidth())
        self.labelOverlapping_2.setSizePolicy(sizePolicy)
        self.labelOverlapping_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelOverlapping_2.setFont(font)
        self.labelOverlapping_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOverlapping_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.labelOverlapping_2.setMargin(-1)
        self.labelOverlapping_2.setObjectName(_fromUtf8("labelOverlapping_2"))
        self.verticalLayout_10.addWidget(self.labelOverlapping_2)
        self.conversionType = QtGui.QComboBox(self.boxAudioEditing)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conversionType.sizePolicy().hasHeightForWidth())
        self.conversionType.setSizePolicy(sizePolicy)
        self.conversionType.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.conversionType.setFont(font)
        self.conversionType.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.conversionType.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.conversionType.setObjectName(_fromUtf8("conversionType"))
        self.conversionType.addItem(_fromUtf8(""))
        self.conversionType.addItem(_fromUtf8(""))
        self.verticalLayout_10.addWidget(self.conversionType)
        self.verticalLayout_4.addLayout(self.verticalLayout_10)
        self.Layout_measurementValues.addWidget(self.boxAudioEditing)
        self.gridLayout_9.addLayout(self.Layout_measurementValues, 0, 0, 1, 1)
        self.toolBoxSettings.addItem(self.Config, _fromUtf8(""))
        self.MeasurementsList = QtGui.QWidget()
        self.MeasurementsList.setGeometry(QtCore.QRect(0, 0, 300, 177))
        self.MeasurementsList.setObjectName(_fromUtf8("MeasurementsList"))
        self.gridLayout_2 = QtGui.QGridLayout(self.MeasurementsList)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.boxMeasurementBtn = QtGui.QGroupBox(self.MeasurementsList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxMeasurementBtn.sizePolicy().hasHeightForWidth())
        self.boxMeasurementBtn.setSizePolicy(sizePolicy)
        self.boxMeasurementBtn.setMinimumSize(QtCore.QSize(300, 100))
        self.boxMeasurementBtn.setMaximumSize(QtCore.QSize(10000, 400))
        self.boxMeasurementBtn.setTitle(_fromUtf8(""))
        self.boxMeasurementBtn.setObjectName(_fromUtf8("boxMeasurementBtn"))
        self.gridLayout_8 = QtGui.QGridLayout(self.boxMeasurementBtn)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.group_measurementManager = QtGui.QGroupBox(self.boxMeasurementBtn)
        self.group_measurementManager.setMaximumSize(QtCore.QSize(200, 200))
        self.group_measurementManager.setTitle(_fromUtf8(""))
        self.group_measurementManager.setObjectName(_fromUtf8("group_measurementManager"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.group_measurementManager)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.btnDelete = QtGui.QPushButton(self.group_measurementManager)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDelete.setFont(font)
        self.btnDelete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDelete.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.verticalLayout_11.addWidget(self.btnDelete)
        self.btnDeleteAll = QtGui.QPushButton(self.group_measurementManager)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnDeleteAll.setFont(font)
        self.btnDeleteAll.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDeleteAll.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnDeleteAll.setObjectName(_fromUtf8("btnDeleteAll"))
        self.verticalLayout_11.addWidget(self.btnDeleteAll)
        self.gridLayout_8.addWidget(self.group_measurementManager, 0, 0, 1, 1)
        self.group_locate = QtGui.QGroupBox(self.boxMeasurementBtn)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_locate.sizePolicy().hasHeightForWidth())
        self.group_locate.setSizePolicy(sizePolicy)
        self.group_locate.setMaximumSize(QtCore.QSize(250, 200))
        self.group_locate.setTitle(_fromUtf8(""))
        self.group_locate.setObjectName(_fromUtf8("group_locate"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.group_locate)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.btnSelect = QtGui.QPushButton(self.group_locate)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btnSelect.setFont(font)
        self.btnSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSelect.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnSelect.setObjectName(_fromUtf8("btnSelect"))
        self.verticalLayout_12.addWidget(self.btnSelect)
        self.btnLocate = QtGui.QPushButton(self.group_locate)
        self.btnLocate.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnLocate.setFont(font)
        self.btnLocate.setObjectName(_fromUtf8("btnLocate"))
        self.verticalLayout_12.addWidget(self.btnLocate)
        self.gridLayout_8.addWidget(self.group_locate, 0, 1, 1, 1)
        self.group_angle = QtGui.QGroupBox(self.boxMeasurementBtn)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_angle.sizePolicy().hasHeightForWidth())
        self.group_angle.setSizePolicy(sizePolicy)
        self.group_angle.setMinimumSize(QtCore.QSize(100, 0))
        self.group_angle.setMaximumSize(QtCore.QSize(150, 16777215))
        self.group_angle.setSizeIncrement(QtCore.QSize(100, 0))
        self.group_angle.setBaseSize(QtCore.QSize(100, 0))
        self.group_angle.setTitle(_fromUtf8(""))
        self.group_angle.setAlignment(QtCore.Qt.AlignCenter)
        self.group_angle.setFlat(False)
        self.group_angle.setObjectName(_fromUtf8("group_angle"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.group_angle)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(9, 0, 9, 9)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.dialAngle = QtGui.QDial(self.group_angle)
        self.dialAngle.setMinimumSize(QtCore.QSize(0, 0))
        self.dialAngle.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dialAngle.setFont(font)
        self.dialAngle.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.dialAngle.setMaximum(359)
        self.dialAngle.setSingleStep(10)
        self.dialAngle.setProperty("value", 0)
        self.dialAngle.setSliderPosition(0)
        self.dialAngle.setTracking(True)
        self.dialAngle.setOrientation(QtCore.Qt.Vertical)
        self.dialAngle.setInvertedAppearance(False)
        self.dialAngle.setInvertedControls(False)
        self.dialAngle.setWrapping(True)
        self.dialAngle.setNotchTarget(10.0)
        self.dialAngle.setNotchesVisible(True)
        self.dialAngle.setObjectName(_fromUtf8("dialAngle"))
        self.verticalLayout_9.addWidget(self.dialAngle)
        self.rotationAngle = QtGui.QSpinBox(self.group_angle)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(120)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotationAngle.sizePolicy().hasHeightForWidth())
        self.rotationAngle.setSizePolicy(sizePolicy)
        self.rotationAngle.setMinimumSize(QtCore.QSize(100, 0))
        self.rotationAngle.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rotationAngle.setMaximum(360)
        self.rotationAngle.setObjectName(_fromUtf8("rotationAngle"))
        self.verticalLayout_9.addWidget(self.rotationAngle)
        self.gridLayout_8.addWidget(self.group_angle, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.boxMeasurementBtn, 0, 0, 1, 1)
        self.listMeasurements = QtGui.QTableWidget(self.MeasurementsList)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listMeasurements.sizePolicy().hasHeightForWidth())
        self.listMeasurements.setSizePolicy(sizePolicy)
        self.listMeasurements.setMinimumSize(QtCore.QSize(300, 0))
        self.listMeasurements.setDragDropOverwriteMode(False)
        self.listMeasurements.setObjectName(_fromUtf8("listMeasurements"))
        self.listMeasurements.setColumnCount(3)
        self.listMeasurements.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.listMeasurements.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.listMeasurements.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.listMeasurements.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.listMeasurements, 1, 0, 1, 1)
        self.toolBoxSettings.addItem(self.MeasurementsList, _fromUtf8(""))
        self.directSoundSelectionLayout = QtGui.QWidget()
        self.directSoundSelectionLayout.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.directSoundSelectionLayout.setObjectName(_fromUtf8("directSoundSelectionLayout"))
        self.gridLayout_3 = QtGui.QGridLayout(self.directSoundSelectionLayout)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.directSoundSelection = MatplotlibWidget(self.directSoundSelectionLayout)
        self.directSoundSelection.setObjectName(_fromUtf8("directSoundSelection"))
        self.gridLayout_3.addWidget(self.directSoundSelection, 0, 0, 1, 1)
        self.toolBoxSettings.addItem(self.directSoundSelectionLayout, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.toolBoxSettings)
        self.dockAudio.setWidget(self.dockWidgetContents)
        IRV360.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockAudio)
        self.dock3d = QtGui.QDockWidget(IRV360)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock3d.sizePolicy().hasHeightForWidth())
        self.dock3d.setSizePolicy(sizePolicy)
        self.dock3d.setMinimumSize(QtCore.QSize(360, 100))
        self.dock3d.setObjectName(_fromUtf8("dock3d"))
        self.widget3d = QtGui.QWidget()
        self.widget3d.setObjectName(_fromUtf8("widget3d"))
        self.dock3d.setWidget(self.widget3d)
        IRV360.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dock3d)
        self.new_project = QtGui.QAction(IRV360)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.new_project.setFont(font)
        self.new_project.setObjectName(_fromUtf8("new_project"))
        self.import_Measurement = QtGui.QAction(IRV360)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.import_Measurement.setFont(font)
        self.import_Measurement.setObjectName(_fromUtf8("import_Measurement"))
        self.actionA_to_B_convertion = QtGui.QAction(IRV360)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionA_to_B_convertion.setFont(font)
        self.actionA_to_B_convertion.setObjectName(_fromUtf8("actionA_to_B_convertion"))
        self.import_Floorplan = QtGui.QAction(IRV360)
        self.import_Floorplan.setObjectName(_fromUtf8("import_Floorplan"))
        self.open_project = QtGui.QAction(IRV360)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.open_project.setFont(font)
        self.open_project.setObjectName(_fromUtf8("open_project"))
        self.save_Project = QtGui.QAction(IRV360)
        self.save_Project.setObjectName(_fromUtf8("save_Project"))
        self.export_to_Plotly = QtGui.QAction(IRV360)
        self.export_to_Plotly.setObjectName(_fromUtf8("export_to_Plotly"))
        self.menuFIle.addAction(self.new_project)
        self.menuFIle.addAction(self.save_Project)
        self.menuFIle.addAction(self.open_project)
        self.menuFIle.addAction(self.export_to_Plotly)
        self.menuImport.addAction(self.import_Floorplan)
        self.menuImport.addAction(self.import_Measurement)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(IRV360)
        self.tabWidget.setCurrentIndex(1)
        self.toolBoxSettings.setCurrentIndex(0)
        self.toolBoxSettings.layout().setSpacing(0)
        QtCore.QMetaObject.connectSlotsByName(IRV360)

    def retranslateUi(self, IRV360):
        IRV360.setWindowTitle(_translate("IRV360", "IRV360", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPressureLevel), _translate("IRV360", "Pressure Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIntensityLevel), _translate("IRV360", "Intensity Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWindowLevel), _translate("IRV360", "Window Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFilter), _translate("IRV360", "Filter", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpectrogram), _translate("IRV360", "Spectrogram", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFloorplan), _translate("IRV360", "Floorplan", None))
        item = self.tableData.horizontalHeaderItem(0)
        item.setText(_translate("IRV360", "Time", None))
        item = self.tableData.horizontalHeaderItem(1)
        item.setText(_translate("IRV360", "Magnitude", None))
        item = self.tableData.horizontalHeaderItem(2)
        item.setText(_translate("IRV360", "Azimuth", None))
        item = self.tableData.horizontalHeaderItem(3)
        item.setText(_translate("IRV360", "Elevation", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTableData), _translate("IRV360", "Data", None))
        self.menuFIle.setTitle(_translate("IRV360", "FIle", None))
        self.menuView.setTitle(_translate("IRV360", "View", None))
        self.menuImport.setTitle(_translate("IRV360", "Import", None))
        self.dockAudio.setWindowTitle(_translate("IRV360", "Settings", None))
        self.btnRecalculate.setText(_translate("IRV360", "RECALCULATE", None))
        self.boxWindowing.setTitle(_translate("IRV360", "Windowing", None))
        self.labelOverlapping.setText(_translate("IRV360", "Overlapping", None))
        self.Overlapping.setItemText(0, _translate("IRV360", "Half overlapped", None))
        self.Overlapping.setItemText(1, _translate("IRV360", "Full overlapped", None))
        self.Overlapping.setItemText(2, _translate("IRV360", "All windows", None))
        self.labelWindowSize.setText(_translate("IRV360", "Window size", None))
        self.windowingWindowSize.setSuffix(_translate("IRV360", " ms", None))
        self.labelQuantity.setText(_translate("IRV360", "Quantity", None))
        self.thresholdLabel.setText(_translate("IRV360", "Threshold", None))
        self.thresholdValue.setSuffix(_translate("IRV360", " dB", None))
        self.boxAudioEditing.setTitle(_translate("IRV360", "Audio Editing", None))
        self.labelAudioCutter.setText(_translate("IRV360", "Audio Cutter", None))
        self.audioCutter.setSuffix(_translate("IRV360", " ms", None))
        self.lowPassFiltering_2.setText(_translate("IRV360", "Filtering", None))
        self.hi_pass_active.setText(_translate("IRV360", "Hi-pass", None))
        self.low_pass_active.setText(_translate("IRV360", "Low-Pass", None))
        self.hiPassFiltering.setSuffix(_translate("IRV360", "KHz", None))
        self.lowPassFiltering.setSuffix(_translate("IRV360", " KHz", None))
        self.labelOverlapping_2.setText(_translate("IRV360", "Conversion type", None))
        self.conversionType.setItemText(0, _translate("IRV360", "Instantaneous", None))
        self.conversionType.setItemText(1, _translate("IRV360", "Applying FFT", None))
        self.toolBoxSettings.setItemText(self.toolBoxSettings.indexOf(self.Config), _translate("IRV360", "Configuration", None))
        self.btnDelete.setText(_translate("IRV360", "Delete", None))
        self.btnDeleteAll.setText(_translate("IRV360", "Delete all", None))
        self.btnSelect.setText(_translate("IRV360", "Select", None))
        self.btnLocate.setText(_translate("IRV360", "Locate", None))
        item = self.listMeasurements.horizontalHeaderItem(0)
        item.setText(_translate("IRV360", "Name", None))
        item = self.listMeasurements.horizontalHeaderItem(1)
        item.setText(_translate("IRV360", "Date", None))
        item = self.listMeasurements.horizontalHeaderItem(2)
        item.setText(_translate("IRV360", "Source", None))
        self.toolBoxSettings.setItemText(self.toolBoxSettings.indexOf(self.MeasurementsList), _translate("IRV360", "Measurements List", None))
        self.toolBoxSettings.setItemText(self.toolBoxSettings.indexOf(self.directSoundSelectionLayout), _translate("IRV360", "Direct Sound Selection", None))
        self.dock3d.setWindowTitle(_translate("IRV360", "3D Visualization", None))
        self.new_project.setText(_translate("IRV360", "New Project", None))
        self.import_Measurement.setText(_translate("IRV360", "Import Measurement", None))
        self.actionA_to_B_convertion.setText(_translate("IRV360", "A to B convertion", None))
        self.import_Floorplan.setText(_translate("IRV360", "Import Floorplan", None))
        self.open_project.setText(_translate("IRV360", "Open Project", None))
        self.save_Project.setText(_translate("IRV360", "Save Project", None))
        self.export_to_Plotly.setText(_translate("IRV360", "Export to Website", None))

from matplotlibwidget import MatplotlibWidget
