# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Fri Nov 18 14:34:49 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1133, 738)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_8 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabPressureLevel = QtGui.QWidget()
        self.tabPressureLevel.setObjectName(_fromUtf8("tabPressureLevel"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabPressureLevel)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.plotPressure = MatplotlibWidget(self.tabPressureLevel)
        self.plotPressure.setObjectName(_fromUtf8("plotPressure"))
        self.gridLayout_6.addWidget(self.plotPressure, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabPressureLevel, _fromUtf8(""))
        self.tabIntensityLevel = QtGui.QWidget()
        self.tabIntensityLevel.setObjectName(_fromUtf8("tabIntensityLevel"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabIntensityLevel)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.plotIntensity = MatplotlibWidget(self.tabIntensityLevel)
        self.plotIntensity.setObjectName(_fromUtf8("plotIntensity"))
        self.gridLayout_7.addWidget(self.plotIntensity, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabIntensityLevel, _fromUtf8(""))
        self.tabSpectogram = QtGui.QWidget()
        self.tabSpectogram.setObjectName(_fromUtf8("tabSpectogram"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabSpectogram)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.plotSpectrogram = MatplotlibWidget(self.tabSpectogram)
        self.plotSpectrogram.setObjectName(_fromUtf8("plotSpectrogram"))
        self.gridLayout_5.addWidget(self.plotSpectrogram, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSpectogram, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.plotIR3D = MatplotlibWidget(self.tab)
        self.plotIR3D.setObjectName(_fromUtf8("plotIR3D"))
        self.gridLayout_9.addWidget(self.plotIR3D, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFIle = QtGui.QMenu(self.menubar)
        self.menuFIle.setObjectName(_fromUtf8("menuFIle"))
        self.menuProcessing = QtGui.QMenu(self.menubar)
        self.menuProcessing.setObjectName(_fromUtf8("menuProcessing"))
        self.menuConfiguration = QtGui.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menuConfiguration.setFont(font)
        self.menuConfiguration.setObjectName(_fromUtf8("menuConfiguration"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuMeasurement = QtGui.QMenu(self.menubar)
        self.menuMeasurement.setObjectName(_fromUtf8("menuMeasurement"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.AudioDock = QtGui.QDockWidget(MainWindow)
        self.AudioDock.setMinimumSize(QtCore.QSize(266, 333))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.AudioDock.setFont(font)
        self.AudioDock.setFloating(False)
        self.AudioDock.setObjectName(_fromUtf8("AudioDock"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(83, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setMouseTracking(True)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(115, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(121, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBox_3.setFont(font)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.spinBox = QtGui.QSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(70, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider.setToolTip(_fromUtf8(""))
        self.horizontalSlider.setStatusTip(_fromUtf8(""))
        self.horizontalSlider.setMaximum(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout.addWidget(self.horizontalSlider, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.AudioDock.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.AudioDock)
        self.measurementDock = QtGui.QDockWidget(MainWindow)
        self.measurementDock.setMinimumSize(QtCore.QSize(275, 173))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.measurementDock.setFont(font)
        self.measurementDock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.measurementDock.setObjectName(_fromUtf8("measurementDock"))
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName(_fromUtf8("dockWidgetContents_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_3 = QtGui.QGroupBox(self.dockWidgetContents_6)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.listView = QtGui.QListView(self.dockWidgetContents_6)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.verticalLayout_4.addWidget(self.listView)
        self.measurementDock.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.measurementDock)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setMinimumSize(QtCore.QSize(842, 84))
        self.dockWidget.setFloating(False)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents_12 = QtGui.QWidget()
        self.dockWidgetContents_12.setObjectName(_fromUtf8("dockWidgetContents_12"))
        self.gridLayout_4 = QtGui.QGridLayout(self.dockWidgetContents_12)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.progressBar_2 = QtGui.QProgressBar(self.dockWidgetContents_12)
        self.progressBar_2.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.gridLayout_4.addWidget(self.progressBar_2, 0, 0, 1, 1)
        self.showDetection = QtGui.QCheckBox(self.dockWidgetContents_12)
        self.showDetection.setObjectName(_fromUtf8("showDetection"))
        self.gridLayout_4.addWidget(self.showDetection, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_12)
        self.label_8.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.comboBox_2 = QtGui.QComboBox(self.dockWidgetContents_12)
        self.comboBox_2.setMinimumSize(QtCore.QSize(120, 32))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_9.addWidget(self.comboBox_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 0, 2, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.dockWidgetContents_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.comboBox_3 = QtGui.QComboBox(self.dockWidgetContents_12)
        self.comboBox_3.setMinimumSize(QtCore.QSize(120, 32))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.horizontalLayout_8.addWidget(self.comboBox_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 0, 3, 1, 1)
        self.btnRecalculate = QtGui.QPushButton(self.dockWidgetContents_12)
        self.btnRecalculate.setMinimumSize(QtCore.QSize(160, 32))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnRecalculate.setFont(font)
        self.btnRecalculate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRecalculate.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btnRecalculate.setObjectName(_fromUtf8("btnRecalculate"))
        self.gridLayout_4.addWidget(self.btnRecalculate, 0, 4, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents_12)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget)
        self.actionNew_project = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionNew_project.setFont(font)
        self.actionNew_project.setObjectName(_fromUtf8("actionNew_project"))
        self.actionImport_Measurement = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionImport_Measurement.setFont(font)
        self.actionImport_Measurement.setObjectName(_fromUtf8("actionImport_Measurement"))
        self.actionA_to_B_convertion = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.actionA_to_B_convertion.setFont(font)
        self.actionA_to_B_convertion.setObjectName(_fromUtf8("actionA_to_B_convertion"))
        self.menuFIle.addAction(self.actionNew_project)
        self.menuFIle.addAction(self.actionImport_Measurement)
        self.menuProcessing.addAction(self.actionA_to_B_convertion)
        self.menubar.addAction(self.menuFIle.menuAction())
        self.menubar.addAction(self.menuMeasurement.menuAction())
        self.menubar.addAction(self.menuProcessing.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPressureLevel), _translate("MainWindow", "Pressure Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabIntensityLevel), _translate("MainWindow", "Intensity Level", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSpectogram), _translate("MainWindow", "Spectrogram", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "IR 3D", None))
        self.menuFIle.setTitle(_translate("MainWindow", "FIle", None))
        self.menuProcessing.setTitle(_translate("MainWindow", "Processing", None))
        self.menuConfiguration.setTitle(_translate("MainWindow", "Configuration", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuMeasurement.setTitle(_translate("MainWindow", "Measurement", None))
        self.AudioDock.setWindowTitle(_translate("MainWindow", "Measurement Config", None))
        self.groupBox.setTitle(_translate("MainWindow", "Audio Editing", None))
        self.label.setText(_translate("MainWindow", "Audio Cutter", None))
        self.doubleSpinBox.setSuffix(_translate("MainWindow", " ms", None))
        self.label_2.setText(_translate("MainWindow", "Low Pass Filtering", None))
        self.doubleSpinBox_2.setSuffix(_translate("MainWindow", " Khz", None))
        self.label_3.setText(_translate("MainWindow", "Band Pass Filtering", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Windowing", None))
        self.label_4.setText(_translate("MainWindow", "Window size", None))
        self.doubleSpinBox_3.setSuffix(_translate("MainWindow", " ms", None))
        self.label_5.setText(_translate("MainWindow", "Quantity", None))
        self.label_6.setText(_translate("MainWindow", "Bounded", None))
        self.label_7.setText(_translate("MainWindow", "Extended", None))
        self.measurementDock.setWindowTitle(_translate("MainWindow", "Measurements", None))
        self.pushButton.setText(_translate("MainWindow", "New ", None))
        self.pushButton_2.setText(_translate("MainWindow", "Edit name", None))
        self.pushButton_3.setText(_translate("MainWindow", "Delete", None))
        self.showDetection.setText(_translate("MainWindow", "Show detections", None))
        self.label_8.setText(_translate("MainWindow", "X Scale", None))
        self.label_9.setText(_translate("MainWindow", "Y Scale", None))
        self.btnRecalculate.setText(_translate("MainWindow", "RECALCULATE", None))
        self.actionNew_project.setText(_translate("MainWindow", "New Project", None))
        self.actionImport_Measurement.setText(_translate("MainWindow", "Import Measurement", None))
        self.actionA_to_B_convertion.setText(_translate("MainWindow", "A to B convertion", None))

from matplotlibwidget import MatplotlibWidget
